routes(
  route("Hello, world!",
        request(uri("/hello")),
        response(text("Hello, world!"))),
  route("Can retrieve all the kittens",
        request(uri("/kittens"),
                method.GET),
        response(text("Some adorable kittens!"))),
  route("Can't make a new kitten",
        request(uri("/kittens"),
                method.POST),
        response(status(422))),
  route("Can update a kitten",
        request(uri("kittens/([0-9]+)"),
                method.PUT),
        response(status(422))),
  route("Person XML",
        request(uri("/person/[0-9]+"),
                method.GET),
        response(xml-file("person.xml"))));